# Note: It's recommended to use `cargo login` instead of storing your token here
# You can run: cargo login your-crates-io-token
# This will store your token securely in ~/.cargo/credentials.toml
#
# [registries]
# [registries.crates-io]
# token = "your-token-goes-here"

# Silence certain lints for dependencies when running clippy
[build]
rustflags = [
    "--cfg", "tokio_unstable",
]

# Allow unstable features in the nightly toolchain
[unstable]
all-features = true